# -*- coding: utf-8 -*-
"""Копия crow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PKYQJmVY81GsgvCJcRV3B3tpY9osH4wP
"""

from google.colab import drive
drive.mount('/content/drive')
video_path = "/content/drive/MyDrive/crow/crowd.mp4"

import cv2
import os
import numpy as np


# Пути
video_path = "/content/drive/MyDrive/crow/crowd.mp4"
output_path = 'output_tracked.mp4'

# Открываем видео
cap = cv2.VideoCapture(video_path)

# Проверяем, удалось ли открыть видео
if not cap.isOpened():
    raise ValueError("Не удалось открыть видеофайл")

# Получаем параметры видео
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = int(cap.get(cv2.CAP_PROP_FPS))

print(f"Видео считывается. FPS: {fps}, Размер кадра: {width}x{height}")

# Настройка VideoWriter
fourcc = cv2.VideoWriter_fourcc(*'mp4v')
out = cv2.VideoWriter(output_path, fourcc, fps, (width, height))

# Проверяем, успешно ли создан VideoWriter
if not out.isOpened():
    raise ValueError("Не удалось создать VideoWriter")

# Установка YOLOv8
!pip install ultralytics

from ultralytics import YOLO

model = YOLO('yolov8l.pt')

# Цикл по кадрам
while True:
    ret, frame = cap.read()
    if not ret:
        break

    # Выполняем детекцию
    results = model(frame, conf=0.6, iou=0.45, verbose=False)

    for result in results:
        boxes = result.boxes
        for box in boxes:
            cls = box.cls.item()
            conf = box.conf.item()

            if cls == 0:
                x1, y1, x2, y2 = map(int, box.xyxy[0])

                # Рисуем прямоугольник
                cv2.rectangle(frame, (x1, y1), (x2, y2), (127, 255, 0), 2)

                # Подпись с уверенностью
                label = f"person {conf:.2f}"
                cv2.putText(frame, label, (x1, y1 - 10),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)

    # Записываем кадр в выходной файл
    out.write(frame)

# Освобождаем ресурсы
cap.release()
out.release()

print("✅ Обработка завершена.")

# Скачивание файла
from google.colab import files
files.download(output_path)